### ISSUE TITLE
Sobre o GIT

### ISSUE THREAD

**Issue by lucianofa** [khayan/gamaacademy-hiringcoders#1]
Olá Khayan!
Eu consigo clonar seu projeto, criar uma nova branch, add, commit e depois dar push aqui?
Fiz uma correção ortográfica mas deu erro de permissão na hora do push --set-upstream origin contribuicao
Estou iniciando no Git e aproveitei seu resumo para testar a interação com outro projeto.

Abraço!

**Comment by khayan** [comment]
Depois de fazer tudo isso você consegue fazer o pull request pra que eu possa aprovar ou não a tua sugestão. O push você vai subir pra tua branch, no teu git. Depois disso pull request a partir do seu repositório, enviando para o original que é o meu, no caso.
